# To open this project in gitpod, visit this URL:
#
# https://gitpod.io/#https://github.com/mvysny/vaadin-boot-example-maven
#

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
# start up tasks
tasks:
- init: ./mvnw -C clean package -Pproduction
  command: ./mvnw -C clean package exec:java
github:
  prebuilds:
    master: true
    branches: true

