# To open this project in gitpod, visit this URL:
#
# https://gitpod.io/#https://github.com/mvysny/vaadin14-embedded-jetty
#

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
# start up tasks
tasks:
- init: ./mvnw clean package -Pproduction
  command: ./mvnw jetty:run
github:
  prebuilds:
    master: true
    branches: true

